package com.example.astrohub

import android.os.Bundle
import android.widget.ImageButton
import android.widget.ImageView
import android.widget.LinearLayout
import android.widget.ScrollView
import android.widget.TextView
import androidx.activity.enableEdgeToEdge
import androidx.appcompat.app.AppCompatActivity
import androidx.core.view.ViewCompat
import androidx.core.view.WindowInsetsCompat
import androidx.viewpager2.widget.ViewPager2

class SsystemActivity : AppCompatActivity() {

    var currentImage = 0
    lateinit var image:ImageView
    var names = arrayOf("Solar System", "Mercury", "Venus", "Earth", "Mars", "Jupiter", "Saturn", "Uranus", "Neptune", "Pluto")
    var paragraphs = arrayOf(
        "The Solar System is centered around the Sun, containing eight planets, dwarf planets like Pluto, moons, asteroids, and comets. The Sun’s immense gravity keeps everything in orbit. Planets are divided into terrestrial (rocky) planets like Mercury, Venus, Earth, and Mars, and gas giants like Jupiter, Saturn, Uranus, and Neptune. Pluto, once the ninth planet, is now classified as a dwarf planet. The Solar System spans vast distances, with the farthest objects lying in the Kuiper Belt and beyond. Solar winds, asteroid belts, and planetary rings are part of its dynamic structure. The heliosphere, a bubble of charged particles, protects the Solar System from cosmic radiation. Exploration continues through telescopes and spacecraft, uncovering its mysteries.",
        "Mercury, the smallest planet and closest to the Sun, has no substantial atmosphere, causing extreme temperature variations. During the day, surface temperatures soar to 430°C, while at night, they drop drastically to -180°C. Mercury’s surface, resembling the Moon, is covered in craters formed by asteroid impacts. It has no moons or rings, and its orbit around the Sun is the fastest, taking only 88 Earth days. With a rotation period of about 59 Earth days and almost no axial tilt, Mercury lacks significant seasons. The planet’s proximity to the Sun and harsh conditions make it challenging to explore. NASA’s MESSENGER mission revealed water ice in permanently shadowed craters, a surprising discovery on this desolate world.",
        "Venus, the second planet from the Sun, is similar in size to Earth but vastly different in nature. It has a dense, carbon dioxide-rich atmosphere that traps heat, resulting in surface temperatures reaching 475°C—hotter than Mercury. Venus’s thick clouds of sulfuric acid reflect sunlight, making it the brightest object in the night sky after the Moon. Unlike most planets, Venus rotates backward, causing its days to be longer than its years. It has no moons or rings and features a volcanic surface with highland regions and plains. The greenhouse effect dominates its climate, creating a scorching, inhospitable environment. Missions like Magellan and Akatsuki study its surface and atmosphere, revealing Venus’s volcanic activity and atmospheric dynamics.",
        "Earth, the third planet from the Sun, is unique for supporting life. Its diverse biosphere includes oceans, forests, mountains, and deserts, which host millions of species. Earth’s atmosphere, composed primarily of nitrogen and oxygen, protects life by blocking harmful radiation. The magnetic field, generated by Earth’s core, shields it from solar winds. Earth has one moon, which affects tides and stabilizes its rotation. The planet’s surface changes constantly due to tectonic activities, erosion, and climate. It rotates once every 24 hours, giving us day and night, and orbits the Sun in 365 days. Earth’s stable temperatures, liquid water, and oxygen-rich air make it the perfect habitat for life as we know it in the universe.",
        "Mars, the fourth planet from the Sun, is known as the Red Planet due to iron oxide (rust) on its surface. It is a cold, desert-like world with temperatures averaging -60°C. Mars has polar ice caps made of water and carbon dioxide, massive dust storms, and the Solar System’s largest volcano, Olympus Mons. Valles Marineris, a canyon system, stretches over 4,000 kilometers. Though its thin atmosphere cannot support liquid water, evidence suggests water once flowed on Mars. Robotic missions like Curiosity and Perseverance are exploring its surface, searching for microbial life. Mars has two small moons, Phobos and Deimos, and it remains a focus for human exploration, with plans to send astronauts in the future.",
        "Jupiter, the fifth planet from the Sun, is the largest in the Solar System. A gas giant, it consists primarily of hydrogen and helium. Jupiter’s iconic Great Red Spot, a storm larger than Earth, has raged for centuries. The planet’s turbulent atmosphere features powerful winds, lightning, and swirling clouds. Jupiter has at least 79 moons, including Ganymede, the largest moon in the Solar System. Its faint ring system, made of dust, is barely visible. Jupiter’s immense gravity influences nearby objects, protecting inner planets by deflecting comets and asteroids. Missions like Galileo and Juno continue to study Jupiter, revealing its internal structure, magnetic field, and stunning cloud patterns, making it one of the most fascinating planets.",
        "Saturn, the sixth planet from the Sun, is famous for its stunning ring system, composed of ice, dust, and rock particles. Saturn is a gas giant primarily made of hydrogen and helium. Despite its size, it has the lowest density of any planet and could theoretically float on water. Saturn has 83 confirmed moons, with Titan being the largest. Titan has a thick atmosphere and lakes of liquid methane. Winds on Saturn can reach speeds of 1,800 kilometers per hour, and its rings are divided into thousands of small ringlets. The Cassini mission provided detailed insights into Saturn’s atmosphere, rings, and moons, revealing its complexity and beauty. Saturn remains a captivating target for planetary exploration.",
        "Uranus, the seventh planet from the Sun, is classified as an ice giant. It has a pale blue-green color due to methane in its atmosphere. Uranus’s most unique feature is its extreme axial tilt of 98 degrees, causing it to rotate sideways and roll along its orbit. This tilt leads to unusual seasons, with each pole experiencing 42 years of continuous sunlight or darkness. Uranus has faint rings and 27 known moons, the largest being Titania and Oberon. Its atmosphere, composed of hydrogen, helium, and methane, reaches frigid temperatures of -224°C, making it the coldest planet. A single orbit takes 84 Earth years, and exploration of Uranus remains limited to observations from telescopes and Voyager 2.",
        "Neptune, the eighth and farthest planet from the Sun, is a frigid ice giant with a striking blue color. Its atmosphere, composed of hydrogen, helium, and methane, features the fastest winds in the Solar System, reaching speeds over 2,000 kilometers per hour. Neptune has a faint ring system and 14 known moons, the largest being Triton, which has geysers of nitrogen ice. A day on Neptune lasts 16 hours, while a full orbit around the Sun takes 165 Earth years. The planet’s interior generates heat, creating violent storms and cloud patterns. Voyager 2 remains the only spacecraft to visit Neptune, capturing its mysterious and dynamic atmosphere, which continues to intrigue astronomers worldwide.",
        "Pluto, located in the Kuiper Belt, is now classified as a dwarf planet. It has a surface of ice and rock, with nitrogen glaciers and mountains made of water ice. Pluto’s thin atmosphere, composed of nitrogen, methane, and carbon monoxide, freezes when it moves farthest from the Sun. Its highly elliptical orbit sometimes brings Pluto closer to the Sun than Neptune. Pluto has five moons, with Charon being the largest, nearly half its size. The New Horizons mission provided detailed images of Pluto’s surface, revealing heart-shaped plains and towering ice mountains. Despite its reclassification, Pluto remains a symbol of curiosity and exploration, representing the outermost reaches of our Solar System."
    )


    override fun onCreate(savedInstanceState: Bundle?) {
        super.onCreate(savedInstanceState)
        setContentView(R.layout.activity_ssystem)

        supportActionBar?.hide()
        val imgPrev = findViewById<ImageButton>(R.id.imgPrev)
        val imgNext = findViewById<ImageButton>(R.id.imgNext)
        val textView = findViewById<TextView>(R.id.textView)
        val textView2 = findViewById<TextView>(R.id.textView2)

        imgPrev.setOnClickListener{
            val idCurrentImageString = "pic$currentImage"
            val idCurrentImageInt = this.resources.getIdentifier(idCurrentImageString,"id",packageName)
            image = findViewById(idCurrentImageInt)
            image.alpha = 0f
            currentImage = (10+currentImage-1)%10

            val idImageShowString = "pic$currentImage"
            val idImageShowInt = this.resources.getIdentifier(idImageShowString,"id",packageName)
            image = findViewById(idImageShowInt)
            image.alpha = 1f
            textView.text = names[currentImage]
            textView2.text = paragraphs[currentImage]
        }
        imgNext.setOnClickListener{
            val idCurrentImageString = "pic$currentImage"
            val idCurrentImageInt = this.resources.getIdentifier(idCurrentImageString,"id",packageName)
            image = findViewById(idCurrentImageInt)
            image.alpha = 0f
            currentImage = (10+currentImage+1)%10

            val idImageShowString = "pic$currentImage"
            val idImageShowInt = this.resources.getIdentifier(idImageShowString,"id",packageName)
            image = findViewById(idImageShowInt)
            image.alpha = 1f
            textView.text = names[currentImage]
            textView2.text = paragraphs[currentImage]
        }
    }
}